const contractABI = [
  {
     "type":"constructor",
     "inputs":[
        {
           "name":"_treasury",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"receive",
     "stateMutability":"payable"
  },
  {
     "type":"function",
     "name":"MAX_FEE",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"balanceOf",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"bulkTransfer",
     "inputs":[
        {
           "name":"_senders",
           "type":"address[]",
           "internalType":"address[]"
        },
        {
           "name":"_recipients",
           "type":"address[]",
           "internalType":"address[]"
        },
        {
           "name":"_amounts",
           "type":"uint256[]",
           "internalType":"uint256[]"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"calculateTransferFee",
     "inputs":[
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"calculateWithdrawalFee",
     "inputs":[
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"contractBalance",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"deposit",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"payable"
  },
  {
     "type":"function",
     "name":"getTreasuryBalance",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"myBalance",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"owner",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"setBalance",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "internalType":"address"
        },
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"setTransferFee",
     "inputs":[
        {
           "name":"_newFee",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"setWithdrawalFee",
     "inputs":[
        {
           "name":"_newFee",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"totalDeposited",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"transfer",
     "inputs":[
        {
           "name":"_to",
           "type":"address",
           "internalType":"address"
        },
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"transferFee",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"transferOwnership",
     "inputs":[
        {
           "name":"_newOwner",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"treasury",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"treasuryBalance",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"updateTreasury",
     "inputs":[
        {
           "name":"_newTreasury",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"withdraw",
     "inputs":[
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"withdrawAll",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"withdrawAllTreasury",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"withdrawTreasury",
     "inputs":[
        {
           "name":"_amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"withdrawalFee",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"event",
     "name":"BulkTransfer",
     "inputs":[
        {
           "name":"from",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"to",
           "type":"address[]",
           "indexed":false,
           "internalType":"address[]"
        },
        {
           "name":"amounts",
           "type":"uint256[]",
           "indexed":false,
           "internalType":"uint256[]"
        },
        {
           "name":"totalFee",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Deposit",
     "inputs":[
        {
           "name":"user",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"amount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"FeeUpdated",
     "inputs":[
        {
           "name":"feeType",
           "type":"string",
           "indexed":false,
           "internalType":"string"
        },
        {
           "name":"oldFee",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        },
        {
           "name":"newFee",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Transfer",
     "inputs":[
        {
           "name":"from",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"to",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"amount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        },
        {
           "name":"fee",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"TreasuryUpdated",
     "inputs":[
        {
           "name":"oldTreasury",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"newTreasury",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"TreasuryWithdrawal",
     "inputs":[
        {
           "name":"to",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"amount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Withdrawal",
     "inputs":[
        {
           "name":"user",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"amount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        },
        {
           "name":"fee",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  }
];

module.exports = contractABI;
